{% set name = "ipyigv" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbafc76b5f92668e68c5a90c388afabf068496060f3e5005ecfbd14192f7a9c8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - jupyter
    - jupyterlab =3
    - jupyter-packaging
    - pip
    - setuptools
    - nodejs
    - yarn
  run:
    - python >=3.0
    - ipywidgets >=7.6.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - spectate

test:
  imports:
    - ipyigv
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-ipyigv/extension.js                                       # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-ipyigv/index.js                                           # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-ipyigv/package.json                                      # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-ipyigv\\extension.js (exit 0) else (exit 1)           # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-ipyigv\\index.js (exit 0) else (exit 1)               # [win]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-ipyigv\\package.json (exit 0) else (exit 1)          # [win]


about:
  home: https://github.com/quantstack/ipyigv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter wrapper for the igv.js library (representation of genomic data)

extra:
  recipe-maintainers:
    - marimeireles
    - SylvainCorlay
    - harrouet
